### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by tbergen1** [SVNCR/Learning_SQL_from_Scratch#1]
### Criteria 1: Report
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*: Your slides are well done.  The give good insight into the problem and good analysis of the issue at hand.  You provided supporting data to bolster your claims regarding the funnel analysis.  I also liked that you included your queries within the report itself as it gives some context to your data.  Lastly, great use of visuals.  The graph at the end summed up your findings nicely and made the data easier to digest rather then it just staying in its numerical form.  Good job here.

### Criteria 2: Query Accuracy
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*: All queries accurately retrieve the data intended.  Great job!

### Criteria 3: Query Formatting
* **Score Level**: 4/4 (Meets Expectations)
* *Comment(s)*: Queries adhere to all of the rules set forth in the style guide.  I would recommend to hold back on some of the commenting though.  While commenting is good, too much can make the queries difficult to read.  I would suggest adding comments before the entire query, and if really necessary, add an inline comment for very specific things.

### Criteria 4: Understanding underlying concepts and terminology
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*: Your report demonstrated an understanding of the concepts of funnel analysis.  Your conclusions and suggestions for what could be done to improve quiz completion were great as well.

### Overall Score: 16/16
Overall, you did a great job with this.  You demonstrated clear understanding of the material and developed a good looking, clean report on your findings.  All of your conclusions were supported with evidence coming from well-formatted, accurate queries.  Keep up the good work!

**Comment by SVNCR** [comment]
Thank you :)
